---
- name: Configure SSH
  ansible.builtin.include_tasks:
    file: ssh.yml

- name: Configure UFW
  ansible.builtin.include_tasks:
    file: ufw.yml

- name: Configure fail2ban
  ansible.builtin.include_tasks:
    file: fail2ban.yml
